name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
          
      - name: Verify repository structure
        run: |
          ls -la
          ls -la lib/ || echo "No lib folder found"
          ls -la api/ || echo "No api folder found"
          
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      # Copy rate-limit.js from wherever it is to api/lib
      - name: Prepare API directory structure
        run: |
          mkdir -p api/lib
          # Try multiple possible locations
          cp lib/rate-limit.js api/lib/ || \
          cp api/../lib/rate-limit.js api/lib/ || \
          cp src/lib/rate-limit.js api/lib/ || \
          echo "Warning: Could not find rate-limit.js"
          ls -la api/lib/
          
      - name: Install API dependencies
        working-directory: api
        run: |
          npm install
          npm install @azure/data-tables
          
      - name: Build Frontend
        run: npm install && npm run build
        
      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_DESERT_05DC5301E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          app_location: "/"
          output_location: "build"
          api_location: "api"
          app_build_command: "npm install && npm run build"
          api_build_command: "cd api && npm install && npm run build"
          action: "upload"